@startuml esp32_interactions

title ESP32 Syncronous Loop Interactions

participant "Actuators" as Actuator
participant "LED" as LED
participant "Receiver" as Receiver
participant "IMU" as IMU
participant "Aircraft" as Aircraft
participant "FlightController" as FlightController
participant "SystemController" as SystemController
participant "Logger" as Logger

== Lettura sensori ==
Receiver -> Aircraft : read(ReceiverData &data)
IMU -> Aircraft : read(ImuData &data)
Aircraft --> FlightController : set input data
Aircraft --> SystemController : set input data

== Controllo globale ==
SystemController -> SystemController : update_state(CONTROLLER_STATE newState)
SystemController -> SystemController : check_errors()
SystemController -> SystemController : update_modes(ReceiverData)
SystemController -> FlightController : State, Mode, Errors

== Controllo del volo ==
FlightController -> FlightController : control(dt, imu_data, receiver_data, output)
FlightController -> SystemController : pass control values

== Aggiornamento output ==
SystemController -> SystemController : set_output(Output &output, ReceiverData &receiver_data, bool imuSetupComplete)
SystemController -> Aircraft : set output data
Aircraft -> Actuator : write()
Aircraft -> LED : update()

== Logging ==
SystemController -> Logger : logData(ImuData, ReceiverData, PID, Output)

@enduml
